name: code_visualizer
description: Visualizes size and change frequency of Dart classes in your codebase.
version: 1.0.0
repository: https://github.com/madicd/code_visualizer

environment:
  sdk: ^3.4.3

dependencies:
  analyzer: ^6.5.0
  path: ^1.9.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
