name: code_visualizer
description: Visualizes size and change frequency of Dart classes in your codebase.
version: 1.0.1
repository: https://github.com/madicd/code_visualizer

executables:
    code_visualizer:

environment:
  sdk: ^3.4.3

dependencies:
  analyzer: ^6.8.0
  path: ^1.9.0

dev_dependencies:
  lints: ^4.0.0
