name: code_visualizer
description: Visualizes size and change frequency of Dart classes in your codebase.
version: 1.0.1
repository: https://github.com/madicd/code_visualizer

executables:
    code_visualizer:

environment:
  sdk: ^3.6.0

dependencies:
  analyzer: ^7.1.0
  path: ^1.9.1

dev_dependencies:
  lints: ^5.1.1
